In [1]:
import numpy as np
import pandas as pd

In [2]:
df_raw = pd.read_csv("data.csv")

df_raw.head()

,gamesPlayed,gamesStarted,minutesPlayed,twoPointersMade,twoPointersAttempted,threePointersMade,threePointersAttempted,offensiveRebounds,defensiveRebounds,totalRebounds,...,steals,turnovers,blocks,freeThrowsMade,freeThrowsAttempted,foulsDrawn,code,name,season,position
0,26.0,0.0,8.480128,0.1,0.4,0.1,0.9,0.2,0.3,0.5,...,0.2,0.4,0.1,0.3,0.4,0.4,007265,"KURUCS, ARTURS",2021,1
1,31.0,3.0,6.978495,0.2,0.5,0.8,2.2,0.0,0.4,0.4,...,0.1,0.2,0.0,0.0,0.1,0.4,004508,"OBST, ANDREAS",2021,1
2,25.0,20.0,10.805333,0.4,0.8,0.6,1.4,0.2,0.6,0.7,...,0.4,0.3,0.1,0.0,0.0,0.1,007338,"UZINSKII, DMITRII",2021,2
3,23.0,2.0,7.260870,0.7,1.4,0.1,0.5,0.2,0.5,0.7,...,0.3,0.7,0.0,0.2,0.3,0.6,011220,"ZIV, IFTAH",2021,1
4,26.0,3.0,12.396154,0.6,1.5,0.3,1.4,0.2,0.4,0.7,...,0.3,0.6,0.1,0.6,0.7,0.8,011204,"GRANT, JERIAN",2021,1

In [5]:
df_filtered = df_raw[(df_raw["minutesPlayed"] >= 10) & (df_raw["gamesPlayed"] >= 10)].reset_index()
print(f"Dropped {len(df_raw) - len(df_filtered)} rows with not enough games/minutes played. Now {len(df_filtered)}.")

Dropped 46 rows with not enough games/minutes played. Now 927.

In [9]:
df_features = pd.DataFrame()

df_features["name"] = df_filtered["name"]
df_features["POS"] = df_filtered["position"]
df_features["3PAr"] = df_filtered["threePointersAttempted"] / ( df_filtered["twoPointersAttempted"] + df_filtered["threePointersAttempted"] )
df_features["3Pr"] = df_filtered["threePointersMade"] / df_filtered["threePointersAttempted"]
df_features["2Pr"] = df_filtered["twoPointersMade"] / df_filtered["twoPointersAttempted"]
df_features["2P"] = df_filtered["twoPointersMade"] / df_filtered["minutesPlayed"] * 40
df_features["FD"] = df_filtered["foulsDrawn"] / df_filtered["minutesPlayed"] * 40
df_features["FTr"] = df_filtered["freeThrowsAttempted"] / ( df_filtered["twoPointersAttempted"] + df_filtered["threePointersAttempted"] )
df_features["AST"] = df_filtered["assists"] / df_filtered["minutesPlayed"] * 40
df_features["TR"] = df_filtered["totalRebounds"] / df_filtered["minutesPlayed"] * 40
df_features["BLK"] = df_filtered["blocks"] / df_filtered["minutesPlayed"] * 40
df_features["AST/TO"] = df_filtered["assists"] / df_filtered["turnovers"]

df_features.head()

,name,POS,3PAr,3Pr,2Pr,2P,FD,FTr,AST,TR,BLK,AST/TO
0,"UZINSKII, DMITRII",2,0.636364,0.428571,0.500000,1.480750,0.370188,0.000000,1.110563,2.591313,0.370188,1.000000
1,"GRANT, JERIAN",1,0.482759,0.214286,0.400000,1.936084,2.581446,0.241379,2.258765,2.258765,0.322681,1.166667
2,"MARINKOVIC, VANJA",2,0.750000,0.333333,0.333333,0.899568,1.499279,0.027778,1.799135,2.698703,0.000000,3.000000
3,"SCHNEIDER, TIM",2,0.612903,0.210526,0.500000,2.038348,1.698623,0.129032,0.679449,7.473942,0.000000,0.400000
4,"MAHMUTOGLU, MELIH",1,0.666667,0.285714,0.571429,2.983179,1.118692,0.119048,1.118692,1.118692,0.000000,1.000000